#!/bin/bash
#
#Desarrollo de un script para detección de conexiones por ssh.
#
#Nos proporcionará información necesaria.
#
#
echo " "
figlet log4me
echo " "
sleep 1.5
echo "$(tput setaf 1)V3rs10n 0.4"
echo ""
echo "Developed by ShadowVMX"
echo " "
echo "https://github.com/ShadowVMX?tab=repositories"
echo " "
sleep 1.5

cat /var/log/auth.log &> /dev/null

if [[ $? == 1 ]] ; then
	echo " "
	echo "$(tput setaf 2)[*]No existe el archivo de log, se generará cuando haya conexiones ssh.[*]"
	echo " "
	echo "[!]Saliendo[!]"
	echo " "
	exit
fi


cat /var/log/auth.log | grep "sshd" &> /dev/null

if [[ $? == 0 ]] ; then
	echo "$(tput setaf 2)"
	echo "[*]---------------------------------------------------------------------[*]"
	echo "[*]                                                                     [*]"
	echo "[*] ¡Hemos encontrado algunos registros de inicio de sesión en el ssh!  [*]"
	echo "[*]                                                                     [*]"
	echo "[*]_____________________________________________________________________[*]"
	echo " "
	echo " "
	sleep 2.5
	echo "$(tput setaf 7)[*]IPs descubiertas tratando de conectarse:  " ; cat /var/log/auth.log | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | sort -u 
	echo ""
	echo " "
	sleep 2.5
	echo "$(tput setaf 7)[*]Conexiones fallidas: " ; cat /var/log/auth.log | cut -d":" -f4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20 | sort | uniq | grep --color -i "failed"
	echo " "
	sleep 2.5
	echo " "
	echo "$(tput setaf 7)[*]Usuarios: " ; grep -oP '(?<=user )[^ ]*' /var/log/auth.log | cut -d "(" -f1 | sort | uniq | grep -v "unknown" 
	sleep 2.5
	echo " "
	echo " "
	echo "$(tput setaf 7)[*]Contraseñas válidas [PELIGRO] " ; cat /var/log/auth.log | cut -d":" -f4,5,6,7,8,9,10,11,12,13,14,151,6,17,18,19,20 | sort | uniq | grep --color -i "Accepted"

fi

if [[ $? == 1 ]] ; then
	echo "$(tput setaf 2)"
	echo "No hemos encontrado registros de ssh login."
	echo " "
fi

